services:
  - type: web
    name: scrumping-map
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python init_db.py  # <-- this line runs your DB init script after installing requirements
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
